// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQBHetXdOTu9CtTRXVOUVMRVj4C1lk3z4',
    appId: '1:550415169981:web:9a1ab9e4f359abdf97fad4',
    messagingSenderId: '550415169981',
    projectId: 'bookmarks-fc53b',
    authDomain: 'bookmarks-fc53b.firebaseapp.com',
    storageBucket: 'bookmarks-fc53b.appspot.com',
    measurementId: 'G-WW87ZC3S6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq5bTBxxh3G_--IhC3zx-0c4wx96jJOWc',
    appId: '1:550415169981:android:7b4c305447e057e697fad4',
    messagingSenderId: '550415169981',
    projectId: 'bookmarks-fc53b',
    storageBucket: 'bookmarks-fc53b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5CDfnsBmZRcBdk8D7PHwlB-q3t4sKfI',
    appId: '1:550415169981:ios:d9270105ab453d5c97fad4',
    messagingSenderId: '550415169981',
    projectId: 'bookmarks-fc53b',
    storageBucket: 'bookmarks-fc53b.appspot.com',
    iosClientId: '550415169981-8dkvjsdaqb01ksr875tpimdqojti5nqf.apps.googleusercontent.com',
    iosBundleId: 'todomore.flutter.firebase.todoFlutterFirebase',
  );
}
